### PR TITLE
#177 Mission&Vision

### PR DESCRIPTION
**Pull request by aleksandarmicev**

### CODE REVIEW

**Comment by RevanchistX** [comment]
@aleksandarmicev 
1. you committed "frames.svg" and "frames.png" but only the png is used. Do we need both images?
2. you added the package "uuid" to dependencies in "package.json", but I don't see it used anywhere. Do we need this?
3. you commented out code in "_colors.scss" - if we don't need this code, delete it.

**Comment by edichoska** [comment]
https://github.com/learnhubmkd/app/assets/105276163/d817488d-bd91-4001-8ffc-a6f390e3855c
Screenshot 2024-05-08 at 21 02 43

The layout looks off on my screen.
The image is distorted. There isn't a margin to separate Mission/Vision from the section above.
The responsiveness on mobile looks okay on iphone 14, but not on the other devices.

@aleksandarmicev

**Comment by edichoska** [comment]
@aleksandarmicev Focus for now on desktop screens to make the image and layout look good and once Dimitar has merged his PR with the fixes for the layout on mobile, you can continue and make improvements.

**Review by RevanchistX — CHANGES_REQUESTED** [review]
Make the change for all images.

**Comment by edichoska** [comment]
Screenshot 2024-05-19 at 01 57 59
Screenshot 2024-05-19 at 01 58 17
Screenshot 2024-05-19 at 01 58 29
Screenshot 2024-05-19 at 01 58 43

On Tablets, the section looks stretched out. You should just add margin block and the text, it shouldn't be 100vh.
- On mobiles we have additional color on top of the section. You may have forgotten to add a background color to the whole section wrapper.
- On smaller desktops it looks like the top and bottom margin are not the same in the Mission/Vision section.
Please take a closer look at the figma file again and compare font sizes, spacings.

**Comment by edichoska** [comment]
Almost done here.
Tablet looks good.
I am seeing some problems on smaller desktops where the section goes outside top and bottom.
On mobile we should have proper padding right.
Screenshot 2024-05-22 at 22 36 45
Screenshot 2024-05-22 at 22 37 00

**Comment by edichoska** [comment]
@aleksandarmicev  Awesome thanks for making the change with the margin.
We need to also remove the padding-top of the Mission Title because we don't need it now, we are controlling the spacing with the margin, and margin + padding results in bigger space on top of the component
Screenshot 2024-05-27 at 14 52 48

**Review by edichoska — APPROVED** [review]
🥇 Kuddos Ace, I think we are done here.
You can merge this PR 🥳

**Comment by edichoska** [comment]
@RevanchistX  please take a look, as well 🙏

**Review by RevanchistX — APPROVED** [review]
LGTM

**Pull request merged**
