### PR TITLE
#289 Project section Design Improvements 

### PR DESCRIPTION
**Pull request by aleksandarmicev**
Changes made in flex wrap and removed 3th card

### CODE REVIEW

**Comment by edichoska** [comment]
@aleksandarmicev  We already have PR for this from @Jasminamih 
Lets merge that one first than double check the figma design if it is the same with our implementation

**Comment by edichoska** [comment]
@aleksandarmicev  We have merged @Jasminamih PR regarding the new design of the Project Section when we only have 2 cards.
Can you please check on staging.learnhub.mk and compare it with the Figma file?
If there are any issues, you should merge staging into this branch to get the newest changes and make the needed changes.

**Comment by aleksandarmicev** [comment]
> @aleksandarmicev We have merged @Jasminamih PR regarding the new design of the Project Section when we only have 2 cards. Can you please check on staging.learnhub.mk and compare it with the Figma file? If there are any issues, you should merge staging into this branch to get the newest changes and make the needed changes.

It looks like the project section is in accordance with the Figma file. Except according Figma design, I suggest more gap for all resolutions or the two cards, like these changes. But if these changes are not acceptable, I purpose we can close this PR because everything else looks okay.

**Comment by edichoska** [comment]
> > @aleksandarmicev We have merged @Jasminamih PR regarding the new design of the Project Section when we only have 2 cards. Can you please check on staging.learnhub.mk and compare it with the Figma file? If there are any issues, you should merge staging into this branch to get the newest changes and make the needed changes.
> 
> It looks like the project section is in accordance with the Figma file. Except according Figma design, I suggest more gap for all resolutions or the two cards, like these changes. But if these changes are not acceptable, I purpose we can close this PR because everything else looks okay.

Than can you merge staging into this branch and make those changes?

**Comment by aleksandarmicev** [comment]
> > > @aleksandarmicev We have merged @Jasminamih PR regarding the new design of the Project Section when we only have 2 cards. Can you please check on staging.learnhub.mk and compare it with the Figma file? If there are any issues, you should merge staging into this branch to get the newest changes and make the needed changes.
> > 
> > 
> > It looks like the project section is in accordance with the Figma file. Except according Figma design, I suggest more gap for all resolutions or the two cards, like these changes. But if these changes are not acceptable, I purpose we can close this PR because everything else looks okay.
> 
> Than can you merge staging into this branch and make those changes?

I made the changes, please check the proposal solution

**Comment by edichoska** [comment]
Screenshot 2024-06-06 at 21 05 32
This is not looking good. Can you please check what happened here?
@aleksandarmicev

**Pull request closed without merging**
