### PR TITLE
#409-Theme-Switch

### PR DESCRIPTION
**Pull request by aleksandarmicev**
Made changes in ThemeContext.tsx and implement Cookies for solving problem with the theme switch.

### CODE REVIEW

**Comment by edichoska** [comment]
@aleksandarmicev we should test this properly on staging first. Please resolve conflicts and lets merge this and test. Then we can release this fix to main.

**Comment by aleksandarmicev** [comment]
> @aleksandarmicev we should test this properly on staging first. Please resolve conflicts and lets merge this and test. Then we can release this fix to main.

I checked this PR and I think that because there is a cookie, running CMD 'npm i' result for eliminating errors. I think the other parts are ok.

Please, let me know if there is a necessary for further adjustments!

**Comment by davorminchorov** [comment]
If you want to test the code on staging, it may be better if you create a `-staging` branch and merge that branch to staging so that this branch remains clean and gets merged into main directly without the need to do any cherry-picking.

**Comment by aleksandarmicev** [comment]
> > If you want to test the code on staging, it may be better if you create a `-staging` branch and merge that branch to staging so that this branch remains clean and gets merged into main directly without the need to do any cherry-picking.
> 
> we don't need this on main. the toogle is working fine on main. there is an issue on staging with the new pages. So the PR should be made towards staging, and we will see if it solves the problem.



Conflict resolved, this PR will go to the staging, according this discussion

**Comment by edichoska** [comment]
@aleksandarmicev Just tested this, works! 🥳  Thanks for the quick fix!

**Review by edichoska — APPROVED** [review]

**Pull request merged**
